#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WEBBANSACH")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_SACH(TBL_SACH instance);
    partial void UpdateTBL_SACH(TBL_SACH instance);
    partial void DeleteTBL_SACH(TBL_SACH instance);
    partial void InsertTBL_THELOAI(TBL_THELOAI instance);
    partial void UpdateTBL_THELOAI(TBL_THELOAI instance);
    partial void DeleteTBL_THELOAI(TBL_THELOAI instance);
    partial void InsertTBL_NXB(TBL_NXB instance);
    partial void UpdateTBL_NXB(TBL_NXB instance);
    partial void DeleteTBL_NXB(TBL_NXB instance);
    partial void InsertTBL_TAIKHOAN(TBL_TAIKHOAN instance);
    partial void UpdateTBL_TAIKHOAN(TBL_TAIKHOAN instance);
    partial void DeleteTBL_TAIKHOAN(TBL_TAIKHOAN instance);
    partial void InsertTBL_HOADON(TBL_HOADON instance);
    partial void UpdateTBL_HOADON(TBL_HOADON instance);
    partial void DeleteTBL_HOADON(TBL_HOADON instance);
    partial void InsertTBL_CHITIET_HOADON(TBL_CHITIET_HOADON instance);
    partial void UpdateTBL_CHITIET_HOADON(TBL_CHITIET_HOADON instance);
    partial void DeleteTBL_CHITIET_HOADON(TBL_CHITIET_HOADON instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this.GetTable<TBL_SACH>();
			}
		}
		
		public System.Data.Linq.Table<TBL_THELOAI> TBL_THELOAIs
		{
			get
			{
				return this.GetTable<TBL_THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NXB> TBL_NXBs
		{
			get
			{
				return this.GetTable<TBL_NXB>();
			}
		}
		
		public System.Data.Linq.Table<TBL_TAIKHOAN> TBL_TAIKHOANs
		{
			get
			{
				return this.GetTable<TBL_TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_HOADON> TBL_HOADONs
		{
			get
			{
				return this.GetTable<TBL_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CHITIET_HOADON> TBL_CHITIET_HOADONs
		{
			get
			{
				return this.GetTable<TBL_CHITIET_HOADON>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SACH")]
	public partial class TBL_SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASACH;
		
		private string _TENSACH;
		
		private string _HINHANH;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private System.Nullable<decimal> _DONGIA;
		
		private string _MANXB;
		
		private string _MATL;
		
		private string _MOTA;
		
		private EntitySet<TBL_CHITIET_HOADON> _TBL_CHITIET_HOADONs;
		
		private EntityRef<TBL_THELOAI> _TBL_THELOAI;
		
		private EntityRef<TBL_NXB> _TBL_NXB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnTENSACHChanging(string value);
    partial void OnTENSACHChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnNGAYNHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnMATLChanging(string value);
    partial void OnMATLChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public TBL_SACH()
		{
			this._TBL_CHITIET_HOADONs = new EntitySet<TBL_CHITIET_HOADON>(new Action<TBL_CHITIET_HOADON>(this.attach_TBL_CHITIET_HOADONs), new Action<TBL_CHITIET_HOADON>(this.detach_TBL_CHITIET_HOADONs));
			this._TBL_THELOAI = default(EntityRef<TBL_THELOAI>);
			this._TBL_NXB = default(EntityRef<TBL_NXB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSACH", DbType="NVarChar(100)")]
		public string TENSACH
		{
			get
			{
				return this._TENSACH;
			}
			set
			{
				if ((this._TENSACH != value))
				{
					this.OnTENSACHChanging(value);
					this.SendPropertyChanging();
					this._TENSACH = value;
					this.SendPropertyChanged("TENSACH");
					this.OnTENSACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="Char(5)")]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					if (this._TBL_NXB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATL", DbType="Char(10)")]
		public string MATL
		{
			get
			{
				return this._MATL;
			}
			set
			{
				if ((this._MATL != value))
				{
					if (this._TBL_THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATLChanging(value);
					this.SendPropertyChanging();
					this._MATL = value;
					this.SendPropertyChanged("MATL");
					this.OnMATLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(1000)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_CHITIET_HOADON", Storage="_TBL_CHITIET_HOADONs", ThisKey="MASACH", OtherKey="MASACH")]
		public EntitySet<TBL_CHITIET_HOADON> TBL_CHITIET_HOADONs
		{
			get
			{
				return this._TBL_CHITIET_HOADONs;
			}
			set
			{
				this._TBL_CHITIET_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_THELOAI_TBL_SACH", Storage="_TBL_THELOAI", ThisKey="MATL", OtherKey="MATL", IsForeignKey=true)]
		public TBL_THELOAI TBL_THELOAI
		{
			get
			{
				return this._TBL_THELOAI.Entity;
			}
			set
			{
				TBL_THELOAI previousValue = this._TBL_THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._TBL_THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_THELOAI.Entity = null;
						previousValue.TBL_SACHes.Remove(this);
					}
					this._TBL_THELOAI.Entity = value;
					if ((value != null))
					{
						value.TBL_SACHes.Add(this);
						this._MATL = value.MATL;
					}
					else
					{
						this._MATL = default(string);
					}
					this.SendPropertyChanged("TBL_THELOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NXB_TBL_SACH", Storage="_TBL_NXB", ThisKey="MANXB", OtherKey="MANXB", IsForeignKey=true)]
		public TBL_NXB TBL_NXB
		{
			get
			{
				return this._TBL_NXB.Entity;
			}
			set
			{
				TBL_NXB previousValue = this._TBL_NXB.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NXB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NXB.Entity = null;
						previousValue.TBL_SACHes.Remove(this);
					}
					this._TBL_NXB.Entity = value;
					if ((value != null))
					{
						value.TBL_SACHes.Add(this);
						this._MANXB = value.MANXB;
					}
					else
					{
						this._MANXB = default(string);
					}
					this.SendPropertyChanged("TBL_NXB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CHITIET_HOADONs(TBL_CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = this;
		}
		
		private void detach_TBL_CHITIET_HOADONs(TBL_CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_THELOAI")]
	public partial class TBL_THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATL;
		
		private string _TENTL;
		
		private EntitySet<TBL_SACH> _TBL_SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATLChanging(string value);
    partial void OnMATLChanged();
    partial void OnTENTLChanging(string value);
    partial void OnTENTLChanged();
    #endregion
		
		public TBL_THELOAI()
		{
			this._TBL_SACHes = new EntitySet<TBL_SACH>(new Action<TBL_SACH>(this.attach_TBL_SACHes), new Action<TBL_SACH>(this.detach_TBL_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATL", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATL
		{
			get
			{
				return this._MATL;
			}
			set
			{
				if ((this._MATL != value))
				{
					this.OnMATLChanging(value);
					this.SendPropertyChanging();
					this._MATL = value;
					this.SendPropertyChanged("MATL");
					this.OnMATLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTL", DbType="NVarChar(50)")]
		public string TENTL
		{
			get
			{
				return this._TENTL;
			}
			set
			{
				if ((this._TENTL != value))
				{
					this.OnTENTLChanging(value);
					this.SendPropertyChanging();
					this._TENTL = value;
					this.SendPropertyChanged("TENTL");
					this.OnTENTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_THELOAI_TBL_SACH", Storage="_TBL_SACHes", ThisKey="MATL", OtherKey="MATL")]
		public EntitySet<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this._TBL_SACHes;
			}
			set
			{
				this._TBL_SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_THELOAI = this;
		}
		
		private void detach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_THELOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NXB")]
	public partial class TBL_NXB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANXB;
		
		private string _TENNXB;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private EntitySet<TBL_SACH> _TBL_SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnTENNXBChanging(string value);
    partial void OnTENNXBChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    #endregion
		
		public TBL_NXB()
		{
			this._TBL_SACHes = new EntitySet<TBL_SACH>(new Action<TBL_SACH>(this.attach_TBL_SACHes), new Action<TBL_SACH>(this.detach_TBL_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNXB", DbType="NVarChar(30)")]
		public string TENNXB
		{
			get
			{
				return this._TENNXB;
			}
			set
			{
				if ((this._TENNXB != value))
				{
					this.OnTENNXBChanging(value);
					this.SendPropertyChanging();
					this._TENNXB = value;
					this.SendPropertyChanged("TENNXB");
					this.OnTENNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="Char(15)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NXB_TBL_SACH", Storage="_TBL_SACHes", ThisKey="MANXB", OtherKey="MANXB")]
		public EntitySet<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this._TBL_SACHes;
			}
			set
			{
				this._TBL_SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NXB = this;
		}
		
		private void detach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NXB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_TAIKHOAN")]
	public partial class TBL_TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TAIKHOAN;
		
		private string _MATKHAU;
		
		private string _HOTEN;
		
		private string _SDT;
		
		private System.Nullable<bool> _QUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnQUYENChanging(System.Nullable<bool> value);
    partial void OnQUYENChanged();
    #endregion
		
		public TBL_TAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(100)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="Bit")]
		public System.Nullable<bool> QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_HOADON")]
	public partial class TBL_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHD;
		
		private string _TENKHACHHANG;
		
		private string _SDT;
		
		private string _DIACHIGIAOHANG;
		
		private System.Nullable<System.DateTime> _NGAYDAT;
		
		private string _TINHTRANG;
		
		private EntitySet<TBL_CHITIET_HOADON> _TBL_CHITIET_HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(int value);
    partial void OnMAHDChanged();
    partial void OnTENKHACHHANGChanging(string value);
    partial void OnTENKHACHHANGChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIGIAOHANGChanging(string value);
    partial void OnDIACHIGIAOHANGChanged();
    partial void OnNGAYDATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDATChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public TBL_HOADON()
		{
			this._TBL_CHITIET_HOADONs = new EntitySet<TBL_CHITIET_HOADON>(new Action<TBL_CHITIET_HOADON>(this.attach_TBL_CHITIET_HOADONs), new Action<TBL_CHITIET_HOADON>(this.detach_TBL_CHITIET_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACHHANG", DbType="NVarChar(50)")]
		public string TENKHACHHANG
		{
			get
			{
				return this._TENKHACHHANG;
			}
			set
			{
				if ((this._TENKHACHHANG != value))
				{
					this.OnTENKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._TENKHACHHANG = value;
					this.SendPropertyChanged("TENKHACHHANG");
					this.OnTENKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHIGIAOHANG", DbType="NVarChar(100)")]
		public string DIACHIGIAOHANG
		{
			get
			{
				return this._DIACHIGIAOHANG;
			}
			set
			{
				if ((this._DIACHIGIAOHANG != value))
				{
					this.OnDIACHIGIAOHANGChanging(value);
					this.SendPropertyChanging();
					this._DIACHIGIAOHANG = value;
					this.SendPropertyChanged("DIACHIGIAOHANG");
					this.OnDIACHIGIAOHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDAT
		{
			get
			{
				return this._NGAYDAT;
			}
			set
			{
				if ((this._NGAYDAT != value))
				{
					this.OnNGAYDATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDAT = value;
					this.SendPropertyChanged("NGAYDAT");
					this.OnNGAYDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(20)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_HOADON_TBL_CHITIET_HOADON", Storage="_TBL_CHITIET_HOADONs", ThisKey="MAHD", OtherKey="MAHD")]
		public EntitySet<TBL_CHITIET_HOADON> TBL_CHITIET_HOADONs
		{
			get
			{
				return this._TBL_CHITIET_HOADONs;
			}
			set
			{
				this._TBL_CHITIET_HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CHITIET_HOADONs(TBL_CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_HOADON = this;
		}
		
		private void detach_TBL_CHITIET_HOADONs(TBL_CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CHITIET_HOADON")]
	public partial class TBL_CHITIET_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHD;
		
		private string _MASACH;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<decimal> _DONGIA;
		
		private System.Nullable<decimal> _THANHTIEN;
		
		private EntityRef<TBL_HOADON> _TBL_HOADON;
		
		private EntityRef<TBL_SACH> _TBL_SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(int value);
    partial void OnMAHDChanged();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnTHANHTIENChanging(System.Nullable<decimal> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public TBL_CHITIET_HOADON()
		{
			this._TBL_HOADON = default(EntityRef<TBL_HOADON>);
			this._TBL_SACH = default(EntityRef<TBL_SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					if (this._TBL_HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					if (this._TBL_SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Money", IsDbGenerated=true)]
		public System.Nullable<decimal> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_HOADON_TBL_CHITIET_HOADON", Storage="_TBL_HOADON", ThisKey="MAHD", OtherKey="MAHD", IsForeignKey=true)]
		public TBL_HOADON TBL_HOADON
		{
			get
			{
				return this._TBL_HOADON.Entity;
			}
			set
			{
				TBL_HOADON previousValue = this._TBL_HOADON.Entity;
				if (((previousValue != value) 
							|| (this._TBL_HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_HOADON.Entity = null;
						previousValue.TBL_CHITIET_HOADONs.Remove(this);
					}
					this._TBL_HOADON.Entity = value;
					if ((value != null))
					{
						value.TBL_CHITIET_HOADONs.Add(this);
						this._MAHD = value.MAHD;
					}
					else
					{
						this._MAHD = default(int);
					}
					this.SendPropertyChanged("TBL_HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_CHITIET_HOADON", Storage="_TBL_SACH", ThisKey="MASACH", OtherKey="MASACH", IsForeignKey=true)]
		public TBL_SACH TBL_SACH
		{
			get
			{
				return this._TBL_SACH.Entity;
			}
			set
			{
				TBL_SACH previousValue = this._TBL_SACH.Entity;
				if (((previousValue != value) 
							|| (this._TBL_SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_SACH.Entity = null;
						previousValue.TBL_CHITIET_HOADONs.Remove(this);
					}
					this._TBL_SACH.Entity = value;
					if ((value != null))
					{
						value.TBL_CHITIET_HOADONs.Add(this);
						this._MASACH = value.MASACH;
					}
					else
					{
						this._MASACH = default(string);
					}
					this.SendPropertyChanged("TBL_SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
