//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach
{

    public partial class tracuu
    {
        protected global::System.Web.UI.WebControls.TextBox txtSDT;
        protected global::System.Web.UI.WebControls.Button btnTraCuu;
        protected global::System.Web.UI.WebControls.Label lbloi;
        protected global::System.Web.UI.WebControls.GridView gvDonHang;
    }
}
